create or replace TABLE RAW.PROPERTY_MANAGEMENT.RENTAL_APPLICATIONS (
	ID NUMBER(38,0) NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL,
	DELETED_AT TIMESTAMP_NTZ(9),
	STATUS VARCHAR(255),
	CONTACT_INFO_ID NUMBER(38,0),
	UPLOADED_AT TIMESTAMP_NTZ(9)
);