create or replace TABLE RAW.PROPERTY_MANAGEMENT.LEASES (
	ID NUMBER(38,0) NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL,
	UNIT_ID NUMBER(38,0),
	START_DATE DATE,
	END_DATE DATE,
	RENTAL_APPLICATION_ID NUMBER(38,0),
	COMPLETED BOOLEAN,
	UPLOADED_AT TIMESTAMP_NTZ(9)
);