create or replace TABLE RAW.PROPERTY_MANAGEMENT.PROPERTIES (
	ID NUMBER(38,0) NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL,
	NAME VARCHAR(255),
	ADDRESS VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(255),
	ZIP_CODE NUMBER(38,0),
	TYPE VARCHAR(255),
	YEAR_BUILT NUMBER(38,0),
	UPLOADED_AT TIMESTAMP_NTZ(9)
);